FROM kalilinux/kali-rolling

# Install essential packages
RUN apt-get update && \
    apt-get full-upgrade -y && \
    apt-get install -y \
        python3 \
        python3-venv \
        python3-pip \
        nmap \
        exploitdb \
        git && \
    rm -rf /var/lib/apt/lists/*

# Create a virtual environment and install Python dependencies
RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --upgrade pip && \
    /opt/venv/bin/pip install python-nmap

# Copy your scanner script into the image
COPY scanner.py /opt/scanner.py
WORKDIR /opt

# Use the virtual environment Python as the default
ENV PATH="/opt/venv/bin:$PATH"

# Use CMD instead of ENTRYPOINT to allow flexible input modes
CMD ["python", "scanner.py"]
