name: VulnScanner CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hari9602/vulnscanner

permissions:  # <-- moved here, top-level for job
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/hari9602/vulnscanner:latest
            ghcr.io/hari9602/vulnscanner:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/Hari9602/VulnScanner
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify pushed image
        run: |
          docker pull ghcr.io/hari9602/vulnscanner:latest
          docker run --rm ghcr.io/hari9602/vulnscanner:latest --help
