name: VulnScanner CI/CD

# Permissions (optional for Docker Hub; required for GHCR)
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: hari9602/vulnscanner  # Replace with your Docker Hub image name

jobs:
  build-push:
    runs-on: ubuntu-latest
    # Skip fork PRs to avoid permission issues
    if: github.event_name == 'push' || github.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify pushed image
        if: github.event_name == 'push'
        run: |
          docker pull ${{ env.IMAGE_NAME }}:latest
          docker run --rm ${{ env.IMAGE_NAME }}:latest --help
